
env: local

http:
  host: localhost
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1

psql:
  host: 127.0.0.1
  port: 5432
  user: kilogram
  password: 112233
  database: app

redis:
  host: 127.0.0.1
  port: 6379
  password: 112233

auth:
  jwt_signing_key: pnMZDLqtHwBnsVqHmCvRBZdBgP6eoQDdIn6mfRyfrdDHqsyK9ofLMfwBvGssPVavYKoMX5W4S6E6Q09KPCX1UAG
  access_token_ttl: 2h
  refresh_token_ttl: 720h #30 days