
env: local

http:
  host: localhost
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1

psql:
  host: 127.0.0.1
  port: 5432
  user: kilogram
  password: 112233
  database: app

auth:
  users_secret: s5v8y/B?E(H+MbQeThWmZq3t6w9z$C&F)J@NcRfUjXn2r5u7x!A%D*G-KaPdSgVk
  users_key: user