definitions:
  models.AccountOut:
    properties:
      birthday:
        type: string
      createdAt:
        type: string
      id:
        type: string
      lastName:
        type: string
      lastVisit:
        type: string
      name:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      updatedAt:
        type: string
    type: object
  models.SignUpAccountInput:
    properties:
      birthday:
        example: "2011-01-11T00:00:00Z"
        type: string
      lastName:
        example: Farkhadov
        minLength: 2
        type: string
      name:
        example: Aziz
        minLength: 2
        type: string
      password:
        maxLength: 60
        minLength: 5
        type: string
      phoneNumber:
        example: "998903456789"
        maxLength: 12
        minLength: 12
        type: string
    required:
    - lastName
    - name
    - password
    - phoneNumber
    type: object
  models.SingInAccountInput:
    properties:
      password:
        maxLength: 60
        minLength: 5
        type: string
      phoneNumber:
        example: "998901231313"
        maxLength: 12
        minLength: 12
        type: string
    required:
    - password
    - phoneNumber
    type: object
  models.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  models.UpdateAccountInput:
    properties:
      lastName:
        example: Farkhadov
        minLength: 2
        type: string
      name:
        example: Aziz
        minLength: 2
        type: string
      password:
        maxLength: 60
        minLength: 5
        type: string
    required:
    - lastName
    - name
    type: object
  v1.Response:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/accounts/:
    put:
      consumes:
      - application/json
      description: This API to update an account.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UpdateAccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccountOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Update an account.
      tags:
      - Accounts
  /api/v1/accounts/me:
    get:
      consumes:
      - application/json
      description: This API to get account by id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccountOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Get account by id.
      tags:
      - Accounts
  /api/v1/accounts/sing-in:
    post:
      consumes:
      - application/json
      description: This API to Sing Up an account.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SingInAccountInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Sing Up an account.
      tags:
      - Accounts
  /api/v1/accounts/sing-up:
    post:
      consumes:
      - application/json
      description: This API to Sing Up an account.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SignUpAccountInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AccountOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Sing Up an account.
      tags:
      - Accounts
swagger: "2.0"
