definitions:
  models.AccountOut:
    properties:
      birthday:
        type: string
      createdAt:
        type: string
      id:
        type: string
      lastName:
        type: string
      lastVisit:
        type: string
      name:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      updatedAt:
        type: string
    type: object
  models.SignUpAccountInput:
    properties:
      birthday:
        example: "2011-01-11T00:00:00Z"
        type: string
      lastName:
        example: Farkhadov
        minLength: 2
        type: string
      name:
        example: Aziz
        minLength: 2
        type: string
      password:
        example: admin
        maxLength: 60
        minLength: 5
        type: string
      phoneNumber:
        example: "998903456789"
        maxLength: 12
        minLength: 12
        type: string
      pinCode:
        example: 1111
        maximum: 9999
        minimum: 1000
        type: integer
    required:
    - lastName
    - name
    - password
    - phoneNumber
    - pinCode
    type: object
  models.SingInAccountInput:
    properties:
      password:
        example: admin123
        maxLength: 60
        minLength: 5
        type: string
      phoneNumber:
        example: "998901231313"
        maxLength: 12
        minLength: 12
        type: string
    required:
    - password
    - phoneNumber
    type: object
  models.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  models.TopUpInput:
    properties:
      amount:
        minimum: 500
        type: number
      pinCode:
        maximum: 9999
        minimum: 1000
        type: integer
    required:
    - amount
    - pinCode
    type: object
  models.TransactionOut:
    properties:
      accountBalance:
        type: number
      accountId:
        type: string
      amount:
        type: number
      createdAt:
        type: string
      id:
        type: string
      method:
        type: string
      reason:
        type: string
      receiver:
        type: string
      sender:
        type: string
    type: object
  models.TransferByPhoneNumberInput:
    properties:
      amount:
        minimum: 500
        type: number
      pinCode:
        maximum: 9999
        minimum: 1000
        type: integer
      receiverPhone:
        example: "998903456789"
        maxLength: 12
        minLength: 12
        type: string
    required:
    - amount
    - pinCode
    - receiverPhone
    type: object
  models.UpdateAccountInput:
    properties:
      lastName:
        example: Farkhadov
        minLength: 2
        type: string
      name:
        example: Aziz
        minLength: 2
        type: string
      password:
        type: string
    required:
    - lastName
    - name
    type: object
  models.WalletOut:
    properties:
      accountId:
        type: string
      balance:
        type: number
      createdAt:
        type: string
      id:
        type: string
      updatedAt:
        type: string
    type: object
  models.WithdrawalFundsInput:
    properties:
      amount:
        minimum: 500
        type: number
      pinCode:
        maximum: 9999
        minimum: 1000
        type: integer
    required:
    - amount
    - pinCode
    type: object
  v1.Response:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: venom.uzz@mail.ru
    name: API Support
    url: https://t.me/xalmatoff
  description: This is a sample server app server.
  title: task
  version: "1.0"
paths:
  /api/v1/accounts/:
    put:
      consumes:
      - application/json
      description: This API to update an account.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UpdateAccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccountOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Update an account.
      tags:
      - Accounts
  /api/v1/accounts/me:
    get:
      consumes:
      - application/json
      description: This API to get account by id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccountOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Get account by id.
      tags:
      - Accounts
  /api/v1/accounts/sing-in:
    post:
      consumes:
      - application/json
      description: This API to Sing Up an account.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SingInAccountInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Sing Up an account.
      tags:
      - Accounts
  /api/v1/accounts/sing-up:
    post:
      consumes:
      - application/json
      description: This API to Sing Up an account.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SignUpAccountInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AccountOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Sing Up an account.
      tags:
      - Accounts
  /api/v1/accounts/wallets/balance:
    get:
      consumes:
      - application/json
      description: This API to get wallet by accountId.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WalletOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Get wallet by accountId.
      tags:
      - Wallets
  /api/v1/accounts/wallets/top-up:
    post:
      consumes:
      - application/json
      description: This API to top up wallet balance.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.TopUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Top up wallet balance.
      tags:
      - Wallets
  /api/v1/accounts/wallets/transfer-by-phone:
    post:
      consumes:
      - application/json
      description: This API to top up wallet balance.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.TransferByPhoneNumberInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Top up transfer funds to account balance ny phone number.
      tags:
      - Wallets
  /api/v1/accounts/wallets/withdrawal:
    post:
      consumes:
      - application/json
      description: This API to Withdrawal Funds from balance.
      parameters:
      - description: data body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.WithdrawalFundsInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Top Withdrawal Funds from balance.
      tags:
      - Wallets
securityDefinitions:
  BearerAuth:
    description: Authorization for accounts
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
